### ISSUE TITLE
Drag not working

### ISSUE THREAD

**Issue by azdevelopment** [u12206050/nova-treeview#2]
vendor.js:1 TypeError: t.parentItem.findIndex is not a function
    at a.onItemDragStart (tree-view:1)
    at dragstart (tree-view:1)
    at It (vendor.js:1)
    at HTMLLIElement.n (vendor.js:1)
    at HTMLLIElement.Qr.o._wrapper (vendor.js:1)

Please help me

**Comment by u12206050** [comment]
What browser are you using? Can you try and create a initial parent probably with `parent_id = null` in the database.

**Comment by azdevelopment** [comment]
i use chrome latest version

**Comment by azdevelopment** [comment]
fixed :)  thank u <3

**Comment by mohammedabdallah** [comment]
@azdevelopment  How did u solve it? I have the same issue even after creating the initial parent  which have parent_id = null
