### ISSUE TITLE
Make fields configurable

### ISSUE THREAD

**Issue by bernhardh** [u12206050/nova-treeview#9]
You expect 3 fields in this package:

```
parent_id
is_active
order
```

Why not make these fields configurable, so that anyone can use their own field names?

Do you accept PR?

**Comment by u12206050** [comment]
Yes will accept PR

**Comment by bernhardh** [comment]
I had a look into it, but actually, tools aren't metaable - see https://github.com/laravel/nova-issues/issues/3142
Of course, I could fetch config in a separate request, but that looks a bit weird to me.

Not sure, but I think, I would prefere to go in another direction and will use a resource tool instead of a tool, which would not only solve this issue, but feels more correct for the whole usecase. So your package isn't the way to go for me.

Thanks anyways.
